menu:

assets:
  cdn: //dn-cdnjscn.qbox.me/
  self:
  
widgets:
- search
- category
- tag
- twitter

excerpt_link: more

github:
  username: jsenjoy

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
domain:

rss:
